export enum SuccessCode {
    // [!] USER
    USER_CREATED = 'USER_CREATED',
    USER_UPDATED = 'USER_UPDATED',
    USER_DELETED = 'USER_DELETED',

    FINISH_TUTORIAL = 'FINISH_TUTORIAL',

    URL_CHANGED = 'URL_CHANGED',

    PROFILE_UPDATED = 'PROFILE_UPDATED',

    // [!] USER SEGMENTS
    SEGMENT_CREATED = 'SEGMENT_CREATED',
    SEGMENT_UPDATED = 'SEGMENT_UPDATED',
    SEGMENT_DELETED = 'SEGMENT_DELETED',
    SUBSCRIPTION_SUCCESS = 'SUBSCRIPTION_SUCCESS',
    SEGMENT_NAME_VALID = 'SEGMENT_NAME_VALID',

    // [!] USER SETTINGS
    EMAIL_VALID = 'EMAIL_VALID',
    PASSWORD_CHANGED = 'PASSWORD_CHANGED',
    PASSWORD_UPDATED = 'PASSWORD_UPDATED',
    AVATAR_UPDATED = 'AVATAR_UPDATED',
    WEB_LOGO_UPDATED = 'WEB_LOGO_UPDATED',

    // [!] POST
    POST_CREATED = 'POST_CREATED',

    // [!] BACKGROUNDS
    BACKGROUND_CREATED = 'BACKGROUND_CREATED',
    BACKGROUND_UPDATED = 'BACKGROUND_UPDATED',
    BACKGROUND_DELETED = 'BACKGROUND_DELETED',
    BACKGROUND_POSITION_CHANGED = 'BACKGROUND_POSITION_CHANGED',
    DEFAULT_BACKGROUND_SYNCED = 'DEFAULT_BACKGROUND_SYNCED',

    // [!] CUSTOMER SUPPORTS
    CUSTOMER_SUPPORT_CREATED = 'CUSTOMER_SUPPORT_CREATED',
    CUSTOMER_SUPPORT_UPDATED = 'CUSTOMER_SUPPORT_UPDATED',
    CUSTOMER_SUPPORT_CLOSED = 'CUSTOMER_SUPPORT_CLOSED',
    CUSTOMER_SUPPORT_DELETED = 'CUSTOMER_SUPPORT_DELETED',

    ATTACHMENTS_UPLOADED = 'ATTACHMENTS_UPLOADED',

    TICKET_REPLIED = 'TICKET_REPLIED',

    // [!] APP INFO
    APP_INFO_CREATED = 'APP_INFO_CREATED',
    APP_INFO_UPDATED = 'APP_INFO_UPDATED',
    APP_INFO_DELETED = 'APP_INFO_DELETED',

    // [!] APP CONFIGS
    APP_CONFIGS_CREATED = 'APP_CONFIGS_CREATED',
    APP_CONFIGS_UPDATED = 'APP_CONFIGS_UPDATED',
    APP_CONFIGS_DELETED = 'APP_CONFIGS_DELETED',

    // [!] PAGE SETTING
    PAGE_SETTING_UPDATED = 'PAGE_SETTING_UPDATED',

    // [!] NOTIFICATION SETTING
    NOTIFICATION_SETTING_UPDATED = 'NOTIFICATION_SETTING_UPDATED',

    // [!] NOTIFICATION
    NOTIFICATION_CREATED = 'NOTIFICATION_CREATED',
    NOTIFICATION_DELETED = 'NOTIFICATION_DELETED',

    // [!] PRODUCT
    PRODUCT_CREATED = 'PRODUCT_CREATED',
    PRODUCT_UPDATED = 'PRODUCT_UPDATED',
    PRODUCT_DELETED = 'PRODUCT_DELETED',

    IMAGES_UPLOADED = 'IMAGES_UPLOADED ',

    // [!] TRANSACTION
    TRANSACTION_COMPONENT_SUCCESS = 'TRANSACTION_COMPONENT_SUCCESS',
    TRANSACTION_PLAN_SUCCESS = 'TRANSACTION_PLAN_SUCCESS',
    TRANSACTION_FAIL = 'TRANSACTION_FAIL',
    POST_LIKED = 'POST_LIKED',
    POST_DELETED = 'POST_DELETED',
    POST_COMMENTED = 'POST_COMMENTED',
    POST_ADDED_TO_FAVORITE = 'POST_ADDED_TO_FAVORITE',
    USER_FOLLOWED = 'USER_FOLLOWED'
}
